# Generated by Django 2.0.1 on 2018-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_tract', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pop_100', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
